### ISSUE TITLE
Update standard references in architecture diagram

### ISSUE THREAD

**Issue by mbtaylor** [ivoa-std/VOUnits#13]
The architechture diagram currently includes DALI (though it's not mentioned in the accompanying Sec 1.1 text), but I don't see much discussion of units in DALI.  Possibly this was down to a misconception of DALI scope at the time of writing VOUnits 1.0?  

Conversely, the diagram does not include VODataService and TAP, which do have placeholders for units (`BaseParam/@unit` attribute and `TAP_SCHEMA.columns` table `unit` field respectively), though the text does make the general observation _"The registry records can also contain units, for the description of table metadata."_   Note however that neither VODataService 1.1 nor TAP 1.1 actually mandate use of VOUnits.

Update the architecture diagram and accompanying text?

**Comment by msdemlei** [comment]
On Thu, Mar 24, 2022 at 07:06:51AM -0700, Mark Taylor wrote:
> Update the architecture diagram and accompanying text?

Yeah, I think that all makes sense.  What do you think of PR #16?

**Comment by mbtaylor** [comment]
I've updated it and approved - sorry should have made that explicit when closing this issue.
