### ISSUE TITLE
Clarify the parsing of unit prefixes (SI or ISO/IEE)

### ISSUE THREAD

**Issue by nxg** [ivoa-std/VOUnits#20]
The grammars in Appx.C talk of 'scalefactor', meaning a numeric scale factor, such as 1e3 permitted in certain places.  However Sect. 2.6 uses the term 'scale factors' to refer to the SI or ISO/IEE prefixes `m`, `M`, `Ki`, and so on.   This is confusing to a careful reader.

Proposal:

  * Reword Sect.2.6 to talk of ‘scaling prefixes’ (is there a better term?).
  * Adjust the first paragraph of Sect. C.4 to mention these prefixes as part of the normative content of the VOUnits syntax.
  * Make it clear (it is currently only implicit) that the scaling prefixes appear in the syntax of Table 21 only as part of the `STRING`: that is, there is in effect an auxiliary parse of this string to separate out the prefix from the unit, known or unknown, that it is prefixing.
  * This may require adjustments to the language of Sect. 1.2 to make sure that the terms so carefully introduced here are in fact consistent with how those same words are used elsewhere.

**Comment by molinaro-m** [comment]
metric prefixes?

**Comment by nxg** [comment]
Hmm: that would work, yes.  We'd have to note that we meant the term to include the ISO/IEE ‘binary prefixes’, `Ki`, `Mi`, and so on, but that's OK.

**Comment by molinaro-m** [comment]
Alternative would be _multipliers_, but makes less sense to me, or repeat "metric and binary prefixes" everywhere (some 40 places I would say).

"Finding" in the document: would it be easier to keep scale factors for SI/IEEE and turn into numeric prefixes all the "numbers" in front of units?
