### ISSUE TITLE
27th CGPM new decimal prefixes

### ISSUE THREAD

**Issue by SebastienDerriere** [ivoa-std/VOUnits#21]
Resolution 3 of the 27th CGPM introduces 4 new decimal prefixes :
https://www.bipm.org/en/cgpm-2022/resolution-3

- 10^{+27} | ronna | R
- 10^{-27} | ronto | r
- 10^{30} | quetta | Q
- 10^{-30} | quecto | q

I don't think they pose any issue with what we have in VOUnits.

R is also used for rayleigh, but because bare unit prefixes are ungrammatical,
I don't think they pose any issue in the parsing.
These could be added to the Table 3 of the VOUnits document.

**Comment by nxg** [comment]
This has been implemented in the unity library ([issue](https://heptapod.host/nxg/unity/-/issues/13)); making the same changes to the text (shortly!) will be very straightforward.

**Comment by nxg** [comment]
Implemented as required
