### ISSUE TITLE
Review the document to note any changes between FITS 3.0 and 4.0

### ISSUE THREAD

**Issue by nxg** [ivoa-std/VOUnits#7]
The [FITS standard](https://fits.gsfc.nasa.gov/fits_standard.html) was updated to 4.0 in 2018.  There should be no major changes, but we should do some brief but systematic check that no changes are necessary (issue #5 refers to a clarification on which is the preferred symbol for year, and that's completed).

**Comment by mbtaylor** [comment]
There is one relevant difference between FITS 3.0 and FITS 4.0, the addition of Section 9.3 _"Time Unit"_ and its attendant Table 34.  This introduces the new units:

* `cy`: Julian century (=`100a`)
* `ta`: tropical year (_"not encouraged"_)
* `Ba`: Besselian year (_"not encouraged"_)

I leave it to VOUnit authors to work out what to do about this.

Having diffed the LaTeX sources, I'm reasonably sure there are no other relevant differences between FITS 3.0 and FITS 4.0.

**Comment by nxg** [comment]
Handled in the Unity library in revision <https://hg.sr.ht/~nxg/unity/rev/3d45e3cd113b6d4ee91360c6eda3ce573001529b>.  Still to have text changes here.

**Comment by nxg** [comment]
Closed in commit 7108c1f
